//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;../EDSIntranet/Images/ico_yield_transp.gif&apos; style=&apos;width:20px; height:17px; padding-right:3px; padding-top:2px&apos;/&gt;.
        /// </summary>
        internal static string AlertIcon {
            get {
                return ResourceManager.GetString("AlertIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing Data......
        /// </summary>
        internal static string MsgAccessingData {
            get {
                return ResourceManager.GetString("MsgAccessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Return to the main page.{1}.
        /// </summary>
        internal static string MsgReturnToMain {
            get {
                return ResourceManager.GetString("MsgReturnToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data records to display..
        /// </summary>
        internal static string NoDataRecordsMessage {
            get {
                return ResourceManager.GetString("NoDataRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Links.
        /// </summary>
        internal static string RelatedLinks {
            get {
                return ResourceManager.GetString("RelatedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {system assigned key}.
        /// </summary>
        internal static string SAK {
            get {
                return ResourceManager.GetString("SAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following field(s) need your attention:.
        /// </summary>
        internal static string ValidationSumHeaderText {
            get {
                return ResourceManager.GetString("ValidationSumHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s New.
        /// </summary>
        internal static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
    }
}
