//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string AccessDenied_description {
            get {
                return ResourceManager.GetString("AccessDenied.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic One - Resources and Downloadables.
        /// </summary>
        internal static string CategoryFourTopicOne_description {
            get {
                return ResourceManager.GetString("CategoryFourTopicOne.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic One - Resources and Downloadables.
        /// </summary>
        internal static string CategoryFourTopicOne_title {
            get {
                return ResourceManager.GetString("CategoryFourTopicOne.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Three - A Form.
        /// </summary>
        internal static string CategoryFourTopicThree_description {
            get {
                return ResourceManager.GetString("CategoryFourTopicThree.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Three - A Form.
        /// </summary>
        internal static string CategoryFourTopicThree_title {
            get {
                return ResourceManager.GetString("CategoryFourTopicThree.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Two - Contacts.
        /// </summary>
        internal static string CategoryFourTopicTwo_description {
            get {
                return ResourceManager.GetString("CategoryFourTopicTwo.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Two - Contacts.
        /// </summary>
        internal static string CategoryFourTopicTwo_title {
            get {
                return ResourceManager.GetString("CategoryFourTopicTwo.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Four.
        /// </summary>
        internal static string CategoryFour_description {
            get {
                return ResourceManager.GetString("CategoryFour.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category four.
        /// </summary>
        internal static string CategoryFour_title {
            get {
                return ResourceManager.GetString("CategoryFour.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and Answers.
        /// </summary>
        internal static string CategoryOneQA_description {
            get {
                return ResourceManager.GetString("CategoryOneQA.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and Answers.
        /// </summary>
        internal static string CategoryOneQA_title {
            get {
                return ResourceManager.GetString("CategoryOneQA.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic One.
        /// </summary>
        internal static string CategoryOneTopicOne_description {
            get {
                return ResourceManager.GetString("CategoryOneTopicOne.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic One.
        /// </summary>
        internal static string CategoryOneTopicOne_title {
            get {
                return ResourceManager.GetString("CategoryOneTopicOne.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Two.
        /// </summary>
        internal static string CategoryOneTopicTwo_description {
            get {
                return ResourceManager.GetString("CategoryOneTopicTwo.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Two.
        /// </summary>
        internal static string CategoryOneTopicTwo_title {
            get {
                return ResourceManager.GetString("CategoryOneTopicTwo.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category One.
        /// </summary>
        internal static string CategoryOne_description {
            get {
                return ResourceManager.GetString("CategoryOne.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category one.
        /// </summary>
        internal static string CategoryOne_title {
            get {
                return ResourceManager.GetString("CategoryOne.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic One - Tables.
        /// </summary>
        internal static string CategoryThreeTopicOne_description {
            get {
                return ResourceManager.GetString("CategoryThreeTopicOne.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic One - Tables.
        /// </summary>
        internal static string CategoryThreeTopicOne_title {
            get {
                return ResourceManager.GetString("CategoryThreeTopicOne.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Three - Glossary.
        /// </summary>
        internal static string CategoryThreeTopicThree_description {
            get {
                return ResourceManager.GetString("CategoryThreeTopicThree.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Three - Glossary.
        /// </summary>
        internal static string CategoryThreeTopicThree_title {
            get {
                return ResourceManager.GetString("CategoryThreeTopicThree.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Two - Images and Icons.
        /// </summary>
        internal static string CategoryThreeTopicTwo_description {
            get {
                return ResourceManager.GetString("CategoryThreeTopicTwo.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Two - Images and Icons.
        /// </summary>
        internal static string CategoryThreeTopicTwo_title {
            get {
                return ResourceManager.GetString("CategoryThreeTopicTwo.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Three.
        /// </summary>
        internal static string CategoryThree_description {
            get {
                return ResourceManager.GetString("CategoryThree.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category three.
        /// </summary>
        internal static string CategoryThree_title {
            get {
                return ResourceManager.GetString("CategoryThree.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Two.
        /// </summary>
        internal static string CategoryTwo_description {
            get {
                return ResourceManager.GetString("CategoryTwo.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category two.
        /// </summary>
        internal static string CategoryTwo_title {
            get {
                return ResourceManager.GetString("CategoryTwo.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_description {
            get {
                return ResourceManager.GetString("Home.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_title {
            get {
                return ResourceManager.GetString("Home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for Something?.
        /// </summary>
        internal static string PageNotFound_description {
            get {
                return ResourceManager.GetString("PageNotFound.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this Site.
        /// </summary>
        internal static string UtilityAbout_description {
            get {
                return ResourceManager.GetString("UtilityAbout.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UtilityAbout_title {
            get {
                return ResourceManager.GetString("UtilityAbout.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us - Thank You.
        /// </summary>
        internal static string UtilityContactConfirm_description {
            get {
                return ResourceManager.GetString("UtilityContactConfirm.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string UtilityContact_description {
            get {
                return ResourceManager.GetString("UtilityContact.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string UtilityContact_title {
            get {
                return ResourceManager.GetString("UtilityContact.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string UtilityMap_description {
            get {
                return ResourceManager.GetString("UtilityMap.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string UtilityMap_title {
            get {
                return ResourceManager.GetString("UtilityMap.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string UtilityOverview_description {
            get {
                return ResourceManager.GetString("UtilityOverview.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string UtilityOverview_title {
            get {
                return ResourceManager.GetString("UtilityOverview.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Preferences.
        /// </summary>
        internal static string UtilityPreferences_description {
            get {
                return ResourceManager.GetString("UtilityPreferences.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string UtilityPreferences_title {
            get {
                return ResourceManager.GetString("UtilityPreferences.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDS Web Privacy and Data Protection Statement.
        /// </summary>
        internal static string UtilityPrivacy_description {
            get {
                return ResourceManager.GetString("UtilityPrivacy.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        internal static string UtilityPrivacy_title {
            get {
                return ResourceManager.GetString("UtilityPrivacy.title", resourceCulture);
            }
        }
    }
}
